# Generated by Django 4.2.30 on 2026-09-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('TMS', 'Train Management System (TMS)'), ('TDMS', 'Train Dispatch Management System (TDMS)'), ('SMMS', 'Station Management and Monitoring System (SMMS)'), ('CTRL', 'Control Management System')], max_length=10),
        ),
    ]
