# Generated by Django 4.2.30 on 2026-09-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdms', '0002_alter_userprofile_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('WORKER', 'Worker User'), ('CTRL', 'Control Officer'), ('STATION', 'Station Master'), ('DIVISION', 'Division Master')], max_length=10),
        ),
    ]
