# Generated by Django 4.2.30 on 2026-09-26 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bdms', '0003_remove_userprofile_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_code', models.CharField(max_length=20, unique=True)),
                ('source', models.CharField(choices=[('AI', 'AI Suggested'), ('WORKER', 'Worker Request')], default='AI', max_length=10)),
                ('section', models.CharField(blank=True, max_length=120)),
                ('km', models.CharField(blank=True, max_length=20)),
                ('asset_type', models.CharField(blank=True, max_length=120)),
                ('asset_code', models.CharField(blank=True, max_length=30)),
                ('work_description', models.CharField(blank=True, max_length=255)),
                ('from_junction', models.CharField(blank=True, max_length=100)),
                ('to_junction', models.CharField(blank=True, max_length=100)),
                ('from_station', models.CharField(blank=True, max_length=100)),
                ('to_station', models.CharField(blank=True, max_length=100)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_critical', models.BooleanField(default=False)),
                ('station_status', models.CharField(choices=[('WAITING', 'Waiting'), ('APPROVED', 'Approved'), ('REJECTED', 'Not Approved')], default='WAITING', max_length=10)),
                ('station_reason', models.CharField(blank=True, max_length=255)),
                ('division_status', models.CharField(choices=[('WAITING', 'Waiting'), ('APPROVED', 'Approved'), ('REJECTED', 'Not Approved')], default='WAITING', max_length=10)),
                ('division_reason', models.CharField(blank=True, max_length=255)),
                ('worker_acceptance', models.CharField(choices=[('WAITING', 'Waiting'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='WAITING', max_length=10)),
                ('worker_reason', models.CharField(blank=True, max_length=255)),
                ('work_status', models.CharField(choices=[('OPEN', 'Open'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('RESCHEDULED', 'Rescheduled'), ('REJECTED', 'Rejected')], default='OPEN', max_length=15)),
                ('reschedule_start', models.DateTimeField(blank=True, null=True)),
                ('reschedule_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_requests', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_department', models.CharField(choices=[('WORKER', 'Worker User'), ('CTRL', 'Control Officer'), ('STATION', 'Station Master'), ('DIVISION', 'Division Master')], max_length=10)),
                ('recipient_department', models.CharField(choices=[('WORKER', 'Worker User'), ('CTRL', 'Control Officer'), ('STATION', 'Station Master'), ('DIVISION', 'Division Master')], max_length=10)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('related_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='bdms.assetrequest')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
