# Generated by Django 4.2.30 on 2026-09-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdms', '0004_assetrequest_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrequest',
            name='division',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='priority',
            field=models.CharField(blank=True, default='Normal', max_length=20),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='work_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
