# Generated by Django 4.2.30 on 2026-09-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdms', '0005_assetrequest_division_assetrequest_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrequest',
            name='section_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='track_line',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='worker_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='worker_role',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
