# Generated by Django 4.2.30 on 2026-09-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdms', '0006_assetrequest_section_code_assetrequest_track_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrequest',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='total_time',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='work_details',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
