# Generated by Django 4.2.30 on 2026-09-28 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bdms', '0009_userprofile_division_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('division', models.CharField(blank=True, max_length=120)),
                ('platforms', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('train_type', models.CharField(choices=[('SUPERFAST', 'Superfast'), ('EXPRESS', 'Express'), ('MAIL', 'Mail'), ('PASSENGER', 'Passenger'), ('SUBURBAN', 'Suburban / Local'), ('FREIGHT', 'Freight'), ('SPECIAL', 'Special')], default='EXPRESS', max_length=12)),
                ('running_days', models.CharField(default='1111111', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='TrainLiveStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('AT_STATION', 'At station'), ('RUNNING', 'Running'), ('TERMINATED', 'Terminated'), ('CANCELLED', 'Cancelled')], default='NOT_STARTED', max_length=12)),
                ('last_seq', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('delay_minutes', models.IntegerField(default=0, help_text='Negative = running early.')),
                ('platform', models.CharField(blank=True, max_length=10)),
                ('last_detected_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=40)),
                ('train', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live', to='bdms.train')),
            ],
        ),
        migrations.CreateModel(
            name='DetectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_seq', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('event', models.CharField(choices=[('ARRIVED', 'Arrived'), ('DEPARTED', 'Departed'), ('PASSED', 'Passed (non-stop)')], max_length=10)),
                ('detected_at', models.DateTimeField()),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('delay_minutes', models.IntegerField(default=0)),
                ('platform', models.CharField(blank=True, max_length=10)),
                ('source', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='bdms.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='bdms.train')),
            ],
            options={
                'ordering': ['-detected_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TrainStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveSmallIntegerField(help_text='Order of the stop, starting at 1.')),
                ('arrival', models.TimeField(blank=True, help_text='Leave empty at the origin station.', null=True)),
                ('departure', models.TimeField(blank=True, help_text='Leave empty at the last station.', null=True)),
                ('day_offset', models.PositiveSmallIntegerField(default=0, help_text='0 = same day the train starts, 1 = next day, ...')),
                ('distance_km', models.PositiveIntegerField(default=0, help_text='Distance from the origin station.')),
                ('platform', models.CharField(blank=True, max_length=10)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stops', to='bdms.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='bdms.train')),
            ],
            options={
                'ordering': ['train', 'seq'],
                'unique_together': {('train', 'seq')},
            },
        ),
    ]
