# Generated by Django 4.2.30 on 2026-09-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdms', '0007_assetrequest_location_assetrequest_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrequest',
            name='reschedule_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
