# Generated by Django 4.2.30 on 2026-09-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdms', '0008_assetrequest_reschedule_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='division',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='section',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='station',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_department',
            field=models.CharField(blank=True, choices=[('SMMS', 'SMMS'), ('TMS', 'TMS'), ('TDMS', 'TDMS')], max_length=10),
        ),
    ]
