# Generated by Django 4.2.30 on 2026-09-29 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bdms', '0010_station_train_trainlivestatus_detectionevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrequest',
            name='ai_note',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_children', to='bdms.assetrequest'),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='trains_checked',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
