# Generated by Django 4.2.30 on 2026-09-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdms', '0011_assetrequest_ai_note_assetrequest_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrequest',
            name='worker_requested_reschedule',
            field=models.BooleanField(default=False),
        ),
    ]
