# Generated by Django 4.2.30 on 2026-09-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdms', '0012_assetrequest_worker_requested_reschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrequest',
            name='rescheduled_by',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
