# Generated by Django 4.2.30 on 2026-10-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdms', '0013_assetrequest_rescheduled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrequest',
            name='control_approved',
            field=models.BooleanField(default=False),
        ),
    ]
