# Generated by Django 4.2.30 on 2026-10-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdms', '0014_assetrequest_control_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrequest',
            name='ai_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainlivestatus',
            name='held_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trainlivestatus',
            name='held_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
