# Generated by Django 4.2.30 on 2026-10-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdms', '0015_assetrequest_ai_approved_trainlivestatus_held_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrequest',
            name='extended_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='extension_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='extension_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
